[package]
name = "image_processing_service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
aws-config = "1.8.3"
aws-sdk-s3 = "1.100.0"
image = "0.25.6"
rand = "0.9.2"
sqlx = "0.8.6"
tokio = { version = "1.46.1", features = ["full"] }
