services:
  postgres:
    image: postgres:17
    container_name: image_processing_service_dev_db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    container_name: image_processing_service_session_store
    ports:
      - "6379:6379"
    volumes:
      - session_data:/data
    restart: unless-stopped

volumes:
    postgres_data:
    session_data: